services:
  e-wallet-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: e-wallet-app:latest
    ports:
      - 9094-9103:9093
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SERVICE_DATASOURCE_POSTGRES_JDBC_URL=jdbc:postgresql://postgres:5432/e_wallet_pg
    networks:
      - e-wallet-network
  postgres:
    container_name: postgres_e_wallet
    image: postgres
    command: postgres -c 'max_connections=120'
    environment:
      POSTGRES_USER: e_wallet_pg
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - e-wallet-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "e_wallet_pg"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
networks:
  e-wallet-network:
    driver: bridge

volumes:
  postgres: