services:
  postgres:
    container_name: postgres_e_wallet
    image: postgres
    environment:
      POSTGRES_USER: e_wallet_pg
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: